[project]
name = "odoo-addons-oca-account-financial-tools"
version = "19.0.20261007.0"
dependencies = [
    "odoo-addon-account_account_tag_code==19.0.*",
    "odoo-addon-account_asset_force_account==19.0.*",
    "odoo-addon-account_asset_management==19.0.*",
    "odoo-addon-account_chart_update==19.0.*",
    "odoo-addon-account_check_deposit==19.0.*",
    "odoo-addon-account_fiscal_position_allowed_journal==19.0.*",
    "odoo-addon-account_fiscal_position_vat_check==19.0.*",
    "odoo-addon-account_fiscal_year==19.0.*",
    "odoo-addon-account_invoice_constraint_chronology==19.0.*",
    "odoo-addon-account_journal_general_sequence==19.0.*",
    "odoo-addon-account_journal_lock_date==19.0.*",
    "odoo-addon-account_journal_restrict_mode==19.0.*",
    "odoo-addon-account_lock_date_update==19.0.*",
    "odoo-addon-account_move_line_tax_editable==19.0.*",
    "odoo-addon-account_move_name_sequence==19.0.*",
    "odoo-addon-account_move_post_date_user==19.0.*",
    "odoo-addon-account_move_print==19.0.*",
    "odoo-addon-account_move_template==19.0.*",
    "odoo-addon-account_move_total_by_account_internal_group==19.0.*",
    "odoo-addon-account_netting==19.0.*",
    "odoo-addon-account_partner_required==19.0.*",
    "odoo-addon-account_payroll_sheet_import==19.0.*",
    "odoo-addon-account_usability==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
